name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start Docker Compose services
        run: |
          docker-compose up -d # Lance les conteneurs en mode détaché

      - name: Wait for containers to start
        run: sleep 10 # Attendre un peu pour que les conteneurs démarrent (ajuste selon ton besoin)

      - name: Check container status
        run: |
          docker-compose ps # Affiche l'état des conteneurs
          # Vérifie qu'aucun conteneur n'a le statut "Exit"
          if docker-compose ps | grep -q "Exit"; then
            echo "Erreur : Certains conteneurs ont échoué !"
            docker-compose logs # Affiche les logs pour debugging
            exit 1
          else
            echo "Tous les conteneurs sont démarrés avec succès !"
          fi

      - name: Clean up
        if: always() # S'exécute même si une étape précédente échoue
        run: |
          docker-compose down # Arrête et supprime les conteneurs